import { MasterDataRow } from './types';

export const MASTER_DATA: MasterDataRow[] = [
  { officeId: "26360015", officeName: "Angul H.O", officeType: "P.O", officeJurisdiction: "Angul H.O", headOfficeName: "Angul H.O", subDivisionName: "Angul East Sub Division", areaType: "Urban" },
  { officeId: "26660617", officeName: "Angul Bazar S.O", officeType: "P.O", officeJurisdiction: "Angul Bazar S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Urban" },
  { officeId: "26660619", officeName: "Athamallik S.O", officeType: "P.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103389", officeName: "Aida B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103395", officeName: "Ambasarmunda B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103468", officeName: "Bhejigotha B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103474", officeName: "Bileinali B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103567", officeName: "Jamudoli B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103599", officeName: "Kampala B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103608", officeName: "Kandhapada B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103620", officeName: "Kantapada B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103664", officeName: "Krutibaspur B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103666", officeName: "Kudugaon B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103689", officeName: "Luhasinga B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103690", officeName: "Lunahandi B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103692", officeName: "Madhapur B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103699", officeName: "Maimura B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103717", officeName: "Nagaon B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103742", officeName: "Paiksahi B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103767", officeName: "Puruna Manitiri B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103775", officeName: "Rainali B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103797", officeName: "Sanahulla B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103839", officeName: "Thakurgarh B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103806", officeName: "Sapaghara B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103648", officeName: "Khambeswaripali B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103711", officeName: "Muchhapur B.O", officeType: "B.O", officeJurisdiction: "Muchhapur B.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103834", officeName: "Taranda B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26103476", officeName: "Bipradihi B.O", officeType: "B.O", officeJurisdiction: "Athamallik S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26660621", officeName: "Bagedia S.O", officeType: "P.O", officeJurisdiction: "Bagedia S.O", headOfficeName: "Angul H.O", subDivisionName: "Angul West Sub Division", areaType: "Rural" },
  { officeId: "26360016", officeName: "Dhenkanal H.O", officeType: "P.O", officeJurisdiction: "Dhenkanal H.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Urban" },
  { officeId: "26660618", officeName: "Anlabereni S.O", officeType: "P.O", officeJurisdiction: "Anlabereni S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660620", officeName: "Badasuanlo S.O", officeType: "P.O", officeJurisdiction: "Badasuanlo S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660623", officeName: "Balimi S.O", officeType: "P.O", officeJurisdiction: "Balimi S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Angul East Sub Division", areaType: "Rural" },
  { officeId: "26660626", officeName: "Bhapur S.O Dhenkanal", officeType: "P.O", officeJurisdiction: "Bhapur S.O Dhenkanal", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660627", officeName: "Bhuban S.O", officeType: "P.O", officeJurisdiction: "Bhuban S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660632", officeName: "Dhenkanal College S.O", officeType: "P.O", officeJurisdiction: "Dhenkanal College S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Urban" },
  { officeId: "26660633", officeName: "Dhenkanal R S S.O", officeType: "P.O", officeJurisdiction: "Dhenkanal R S S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Urban" },
  { officeId: "26660634", officeName: "Gadasila S.O", officeType: "P.O", officeJurisdiction: "Gadasila S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660635", officeName: "Gondiapatna S.O", officeType: "P.O", officeJurisdiction: "Gondiapatna S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660637", officeName: "Govindpur S.O (Dhenkanal)", officeType: "P.O", officeJurisdiction: "Govindpur S.O (Dhenkanal)", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660639", officeName: "Hindol Road R.S. S.O", officeType: "P.O", officeJurisdiction: "Hindol Road R.S. S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660640", officeName: "Hindol S.O", officeType: "P.O", officeJurisdiction: "Hindol S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Angul East Sub Division", areaType: "Rural" },
  { officeId: "26660645", officeName: "Jubuli Town S.O", officeType: "P.O", officeJurisdiction: "Jubuli Town S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Urban" },
  { officeId: "26660646", officeName: "Kamakhyanagar S.O", officeType: "P.O", officeJurisdiction: "Kamakhyanagar S.O", headOfficeName: "Dhenkanal Division", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Urban" },
  { officeId: "26660648", officeName: "Kankadahad S.O", officeType: "P.O", officeJurisdiction: "Kankadahad S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660652", officeName: "Mahabirod S.O", officeType: "P.O", officeJurisdiction: "Mahabirod S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660653", officeName: "Mahimagadi S.O", officeType: "P.O", officeJurisdiction: "Mahimagadi S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Dhenkanal Sub Division", areaType: "Rural" },
  { officeId: "26660654", officeName: "Marthapur S.O", officeType: "P.O", officeJurisdiction: "Marthapur S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660655", officeName: "Mathakargola S.O", officeType: "P.O", officeJurisdiction: "Mathakargola S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660656", officeName: "Meramandali S.O", officeType: "P.O", officeJurisdiction: "Meramandali S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Angul East Sub Division", areaType: "Rural" },
  { officeId: "26660662", officeName: "Parjang S.O", officeType: "P.O", officeJurisdiction: "Parjang S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Kamakhya Nagar Sub Division", areaType: "Rural" },
  { officeId: "26660664", officeName: "Rasol S.O", officeType: "P.O", officeJurisdiction: "Rasol S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Angul East Sub Division", areaType: "Rural" },
  { officeId: "26660670", officeName: "Talmul S.O", officeType: "P.O", officeJurisdiction: "Talmul S.O", headOfficeName: "Dhenkanal H.O", subDivisionName: "Angul East Sub Division", areaType: "Rural" },
];

export const PRODUCTS = {
  DOMESTIC: [
    'Inland Speed Post',
    'Gyan Post', 
    'Inland Speed Post Document', 
    'Registered Letter'
  ],
  PARCEL: [
    'India Post Parcel Retail',
    'Indiapost parcel Retail', 
    'Indiapost Parcel Contractual', 
    'Speed Post Parcel Domestic',
    'Speedpost parcel Retail',
    'Speed Post Parcel Retail'
  ],
  INTERNATIONAL: [
    'International Air Parcel',
    'International Speed Post Document',
    'International Speed Post Merchandise',
    'Registered Foreign Letter',
    'Registered International Small Packets',
    'International Registered Letter'
  ],
  ALL: [
    'Inland Speed Post',
    'Gyan Post',
    'Inland Speed Post Document',
    'Registered Letter',
    'India Post Parcel Retail',
    'Indiapost Parcel Contractual',
    'Speed Post Parcel Domestic',
    'International Air Parcel',
    'International Speed Post Document',
    'International Speed Post Merchandise',
    'Registered Foreign Letter',
    'Registered International Small Packets',
    'International Registered Letter'
  ]
};